# Generated by Django 6.0 on 2025-12-09 03:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='publicado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
